name: test

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: check some build related things
        run: |
          git --version
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git status
          git diff
          ls -la .

      - name: specifically set a tag of v2.0.1
        id: version
        run: ./version-bump.sh
        env:
          GHA_TAG: v2.0.1

      - name: test to see if the exact tag is returned
        run: |
          if [[ "$version_tag_numeric" == '2.0.1' ]];then
            echo "winning"
          else
            exit 1
          fi

        shell: bash
        env:
          version_tag_numeric: ${{ steps.version.outputs.version_tag_numeric }}
          version_tag: ${{ steps.version.outputs.version_tag }}

      - name: test to see if default patch bumping from the latest git tag of 0.0.1 works
        id: version_bumped
        run: ./version-bump.sh
        env:
          GHA_TAG: latest

      - name: test if 0.0.1 is bumped to 0.0.2
        run: |
          if [[ "$version_tag_numeric" == '0.0.2' ]];then
            echo "winning"
          else
            exit 1
          fi

        shell: bash
        env:
          version_tag_numeric: ${{ steps.version_bumped.outputs.version_tag_numeric }}
          version_tag: ${{ steps.version_bumped.outputs.version_tag }}


      - name: commit '#minor' to the local git repo (no push)
        run: |
          git --version
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          touch wibble
          echo 'bibble' > wibble
          git add wibble
          git commit -m '#minor'

      - name: bump 0.0.1 to 0.1.0 using the '#minor' tag
        id: version_bumped_gitlog_minor
        run: ./version-bump.sh
        env:
          GHA_TAG: latest

      - name: test that minor bump has happened to 0.1.0
        run: |
          if [[ "$version_tag_numeric" == '0.1.0' ]];then
            echo "winning"
          else
            exit 1
          fi
        shell: bash
        env:
          version_tag_numeric: ${{ steps.version_bumped_gitlog_minor.outputs.version_tag_numeric }}
          version_tag: ${{ steps.version_bumped_gitlog_minor.outputs.version_tag }}

