name: test

on:
  workflow_call:
    inputs:
      version_tag:
        description: 'Name of the tag to build'
        required: false
        default: "v2.0.1"
        type: string

  workflow_dispatch:
    inputs:
      version_tag:
        description: 'Name of the tag to build'
        required: false
        default: "v2.0.1"
        type: string

  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: check some build related things
        run: |
          git --version
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git status
          git diff
          ls -la .

      - name: find next version
        id: version
        uses: ORCID-dev/version-bump-action@main
        with:
          version_tag: ${{ inputs.version_tag }}

      - name: test if keeping vars are right
        run: |
          if [[ "$version_tag_numeric" == '2.0.1' ]];then
            echo "winning"
          else
            exit 1
          fi

        shell: bash
        env:
          version_tag_numeric: ${{ steps.version.outputs.version_tag_numeric }}
          version_tag: ${{ steps.version.outputs.version_tag }}

      - name: find next version
        id: version_bumped
        uses: ORCID-dev/version-bump-action@main
        with:
          version_tag: next_tag

      - name: test if bumping vars are right
        run: |
          if [[ "$version_tag_numeric" == '0.0.2' ]];then
            echo "winning"
          else
            exit 1
          fi

        shell: bash
        env:
          version_tag_numeric: ${{ steps.version_bumped.outputs.version_tag_numeric }}
          version_tag: ${{ steps.version_bumped.outputs.version_tag }}




